# Generated by Django 2.2.1 on 2019-05-22 08:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('triplog', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trip',
            name='trip_category',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='triplog.Category'),
        ),
        migrations.AlterField(
            model_name='trip',
            name='trip_location',
            field=models.ManyToManyField(blank=True, to='triplog.Location'),
        ),
    ]
