# Generated by Django 2.2.1 on 2019-06-13 03:24

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('triplog', '0002_auto_20190522_0804'),
    ]

    operations = [
        migrations.AddField(
            model_name='location',
            name='location_date',
            field=models.DateTimeField(blank=True, default=datetime.datetime.now, verbose_name='location date'),
        ),
        migrations.AddField(
            model_name='trip',
            name='trip_date',
            field=models.DateTimeField(blank=True, default=datetime.datetime.now, verbose_name='trip date'),
        ),
    ]
