# Generated by Django 2.2.1 on 2019-06-17 01:19

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('triplog', '0003_auto_20190613_0324'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trip',
            name='trip_category',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='category_set', to='triplog.Category'),
        ),
        migrations.AlterField(
            model_name='trip',
            name='trip_location',
            field=models.ManyToManyField(blank=True, related_name='location_set', to='triplog.Location'),
        ),
        migrations.AlterField(
            model_name='trip',
            name='trip_user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_set', to=settings.AUTH_USER_MODEL),
        ),
    ]
